Projeto Cobmais/Models/ProjetoCalculoDivida.cs
namespace Projeto_Cobmais.Models
{
    using Microsoft.EntityFrameworkCore;

    public class ProjetoCalculoDivida
    {
        public string Cpf { get; set; } // Chave primária
        public string Cliente { get; set; }
        public string Numero_Contrato { get; set; }
        public DateTime Vencimento { get; set; }
        public float Valor { get; set; }
        public string Tipo_de_Contrato { get; set; }
        public float Valor_Original { get; set; }
        public float Valor_Atualizado { get; set; }
        public float Valor_Desconto { get; set; }
    }
    // Contexto do banco de dados
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

        // DbSet representa a tabela no banco de dados
        public DbSet<ProjetoCalculoDivida> CalculoDividas { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ProjetoCalculoDivida>()
                .HasKey(e => e.Cpf); // Define explicitamente a chave primária
        }
    }
}

Projeto Cobmais/Controllers/ArquivoController.cs
using Microsoft.AspNetCore.Mvc;
using Projeto_Cobmais.Models;

namespace Projeto_Cobmais.Controllers
{
    public class ArquivoController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            List<ArquivoDTO> arquivos;

            try
            {
                arquivos = new ArquivoModel().RecuperarDadosArquivos();
            }
            catch (Exception ex)
            {
                arquivos = new();
                ViewData["Exception"] = $"Ocorreu um erro ao buscar os arquivos: {ex.Message}";
            }

            return View("Index", arquivos);
        }

        [HttpGet]
        public RetornoAjax<string> RecuperarConteudo(int id)
        {
            RetornoAjax<string> result = new();

            try
            {
                result.Objeto = new ArquivoModel().RecuperarConteudo(id);
                result.Status = !string.IsNullOrEmpty(result.Objeto);
            }
            catch (Exception ex)
            {
                result.Mensagem[DictionaryHelper.Inconsistencias] = $"Ocorreu um erro ao buscar o conteúdo do arquivo: {ex.Message}";
                result.Exception = true;
                throw;
            }

            return result;
        }

        [HttpPost]
        public RetornoAjax<ArquivoDTO> Importar()
        {
            RetornoAjax<ArquivoDTO> result = new();

            try
            {
                new ArquivoModel().Importar(result);
            }
            catch (Exception ex)
            {
                result.Exception = true;
                result.Mensagem[DictionaryHelper.Inconsistencias] = "Ocorreu um erro ao importar: " + ex.Message;
            }

            return result;
        }

        [Route("/Arquivo/Detalhes")]
        public IActionResult Detalhes(int id)
        {
            ArquivoDTO arquivoDTO = new();

            try
            {
                arquivoDTO = new ArquivoModel().RecuperarDadosArquivos(new int[] { id }).ElementAtOrDefault(0);

                if (arquivoDTO == null)
                    ViewData["Exception"] = "Não foi possível encontrar o arquivo";

            }
            catch (Exception ex)
            {
                ViewData["Exception"] = "Ocorreu um erro ao buscar o arquivo: " + ex.Message;
            }

            return View(arquivoDTO);
        }
    }
}

Projeto Cobmais/Controllers/CalculoDividaController.cs
using Microsoft.AspNetCore.Mvc;
using Projeto_Cobmais.Models;
using System.Globalization;


namespace Projeto_Cobmais.Controllers
{
    public class CalculoDividaController : Controller
    {
        private readonly AppDbContext _context;

        public CalculoDividaController(AppDbContext context)
        {
            /* É usado em todo o controlador para acessar ou manipular dados no banco de dados. */
            _context = context;
        }

        // GET: Exibe o formulário para upload
        [HttpGet]
        public IActionResult Upload()
        {
            return View("~/Pages/Upload.cshtml");
        }

        // POST: Processa o arquivo CSV e salva os dados no banco
        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile csvFile)
        {
            if (csvFile == null || csvFile.Length == 0)
            {
                ModelState.AddModelError("", "Por favor, selecione um arquivo CSV válido.");
                return View();
            }

            var registros = new List<ProjetoCalculoDivida>();

            using (var reader = new StreamReader(csvFile.OpenReadStream()))
            {
                while (!reader.EndOfStream)
                {
                    var line = await reader.ReadLineAsync();
                    var values = line.Split(',');

                    // O Arquivo precisa ter 6 registros passar
                    if (values.Length != 6)
                        continue;

                    DateTime vencimento = DateTime.ParseExact(values[3], "dd/MM/yyyy", CultureInfo.InvariantCulture);

                    // Cria um registro com os dados do CSV
                    registros.Add(new ProjetoCalculoDivida
                    {
                        Cpf = values[0],
                        Cliente = values[1],
                        Numero_Contrato = values[2],
                        Vencimento = vencimento,
                        Valor = float.Parse(values[4]),
                        Tipo_de_Contrato = values[5],
                    });
                }
            }

            // Salva os registros no banco
            _context.CalculoDividas.AddRange(registros);
            await _context.SaveChangesAsync();

            ViewBag.Message = "Arquivo processado e dados salvos com sucesso!";
            return View();
        }

        // GET: Exibe a lista de cálculos de dívidas
        [HttpGet]
        public IActionResult Lista()
        {
            var calculoDividas = _context.CalculoDividas.ToList();
            return View(calculoDividas);
        }
    }
}

Projeto Cobmais/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Projeto_Cobmais.Models;

namespace Projeto_Cobmais.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Projeto Cobmais/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Projeto_Cobmais.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Projeto Cobmais/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Projeto_Cobmais.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Projeto Cobmais/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Projeto_Cobmais.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Projeto Cobmais/Pages/Upload.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Projeto_Cobmais.Pages
{
    public class UploadModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Projeto Cobmais/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Cálculo Dívida</h1>

    @Html.Partial("Upload")

    <a type="button" class="btn btn-primary">Exportar</a>
</div>

Projeto Cobmais/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto_Cobmais</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projeto_Cobmais.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Projeto_Cobmais</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Projeto_Cobmais - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Projeto Cobmais/Pages/Upload.cshtml
@{
    ViewBag.Title = "Upload de Arquivo CSV";
}

<h2>Upload de Arquivo CSV</h2>

<form asp-action="Upload" asp-controller="CalculoDivida" method="post" enctype="multipart/form-data">
    <div>
        <label for="csvFile">Selecione o arquivo CSV:</label>
        <input type="file" id="csvFile" name="csvFile" accept=".csv" />
    </div>
    <br />
    <button type="submit">Enviar</button>
</form>

@if (ViewBag.Message != null)
{
    <p style="color: green;">@ViewBag.Message</p>
}